### ISSUE TITLE
Realidad Aumentada WebAR

### ISSUE THREAD

**Issue by Band-hi** [SistemasTecTlaxiaco/actividad-5-realidad-aumentada-en-sitio-web-remi-team-1#1]
[Reporte 3 - Realidad Aumentada.pdf](https://github.com/SistemasTecTlaxiaco/actividad-5-realidad-aumentada-en-sitio-web-remi-team-1/files/11107349/Reporte.3.-.Realidad.Aumentada.pdf)

**Comment by Yabin-2021** [comment]
Calificación: 20/20

**Comment by josealfredo79** [comment]
Bien hecho y revisado
